DROP DATABASE IF EXISTS "arca-1";
DROP DATABASE IF EXISTS "arca-2";
DROP DATABASE IF EXISTS "arca-3";
DROP DATABASE IF EXISTS "arca-4";

CREATE DATABASE "arca-1" WITH OWNER=arca;
CREATE DATABASE "arca-2" WITH OWNER=arca;
CREATE DATABASE "arca-3" WITH OWNER=arca;
CREATE DATABASE "arca-4" WITH OWNER=arca;